name: first github action
run-name: first one
on: pull_request
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: checking out repo
        uses: actions/checkout@v4

      - name: print welcome message
        run: echo "Hello Github Actions"

      - name: list present directory
        run: pwd

      - name: list the files
        run: ls -lhrt
